//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase_First
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentId { get; set; }
        public string Sujet { get; set; }
        public System.DateTime DateCreation { get; set; }
        public string Email { get; set; }
        public Nullable<int> ToDo_ToDoId { get; set; }
    
        public virtual ToDo ToDo { get; set; }
    }
}
